### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by williambj1** [williambj1/GenI2C#5]
- [ ] Redesign ToolBar Icon
- [ ] Add support for generations before Skylake
- [ ] Support duel touching devices (patch at the same time)
- [ ] Support information detection on the home page for duel touching devices
- [ ] Support Skylake I2C Controller Patch
- [ ] Use the read CPU information to select the architecture automatically
- [ ] Add a preference menu for patching options
- [ ] Support Drag and Drop to read the file's path
- [ ] Analyze VoodooI2C logs and shoot issues 
- [ ] Write a guide
